# Generated by Django 3.0.7 on 2020-06-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_auto_20200614_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
    ]
