# Generated by Django 3.0.7 on 2020-06-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0017_auto_20200614_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
    ]
