# Generated by Django 3.0.7 on 2020-06-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0018_remove_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=models.TextField()),
        ),
    ]
